# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'aa.ui',
# licensing of 'aa.ui' applies.
#
# Created: Sun Oct  7 18:03:10 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_aaWindow(object):
    def setupUi(self, aaWindow):
        aaWindow.setObjectName("aaWindow")
        aaWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(aaWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 80, 801, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.GLU = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLU.sizePolicy().hasHeightForWidth())
        self.GLU.setSizePolicy(sizePolicy)
        self.GLU.setObjectName("GLU")
        self.gridLayout.addWidget(self.GLU, 1, 1, 1, 1)
        self.GLN = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLN.sizePolicy().hasHeightForWidth())
        self.GLN.setSizePolicy(sizePolicy)
        self.GLN.setObjectName("GLN")
        self.gridLayout.addWidget(self.GLN, 1, 2, 1, 1)
        self.ALA = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ALA.sizePolicy().hasHeightForWidth())
        self.ALA.setSizePolicy(sizePolicy)
        self.ALA.setObjectName("ALA")
        self.gridLayout.addWidget(self.ALA, 0, 0, 1, 1)
        self.ASP = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ASP.sizePolicy().hasHeightForWidth())
        self.ASP.setSizePolicy(sizePolicy)
        self.ASP.setObjectName("ASP")
        self.gridLayout.addWidget(self.ASP, 0, 3, 1, 1)
        self.HIS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HIS.sizePolicy().hasHeightForWidth())
        self.HIS.setSizePolicy(sizePolicy)
        self.HIS.setObjectName("HIS")
        self.gridLayout.addWidget(self.HIS, 2, 0, 1, 1)
        self.pushButton_17SER = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17SER.sizePolicy().hasHeightForWidth())
        self.pushButton_17SER.setSizePolicy(sizePolicy)
        self.pushButton_17SER.setObjectName("pushButton_17SER")
        self.gridLayout.addWidget(self.pushButton_17SER, 3, 3, 1, 1)
        self.MET = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MET.sizePolicy().hasHeightForWidth())
        self.MET.setSizePolicy(sizePolicy)
        self.MET.setObjectName("MET")
        self.gridLayout.addWidget(self.MET, 3, 0, 1, 1)
        self.LYS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LYS.sizePolicy().hasHeightForWidth())
        self.LYS.setSizePolicy(sizePolicy)
        self.LYS.setObjectName("LYS")
        self.gridLayout.addWidget(self.LYS, 2, 3, 1, 1)
        self.TRP = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TRP.sizePolicy().hasHeightForWidth())
        self.TRP.setSizePolicy(sizePolicy)
        self.TRP.setObjectName("TRP")
        self.gridLayout.addWidget(self.TRP, 4, 1, 1, 1)
        self.ILE = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ILE.sizePolicy().hasHeightForWidth())
        self.ILE.setSizePolicy(sizePolicy)
        self.ILE.setObjectName("ILE")
        self.gridLayout.addWidget(self.ILE, 2, 1, 1, 1)
        self.LEU = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LEU.sizePolicy().hasHeightForWidth())
        self.LEU.setSizePolicy(sizePolicy)
        self.LEU.setObjectName("LEU")
        self.gridLayout.addWidget(self.LEU, 2, 2, 1, 1)
        self.VAL = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VAL.sizePolicy().hasHeightForWidth())
        self.VAL.setSizePolicy(sizePolicy)
        self.VAL.setObjectName("VAL")
        self.gridLayout.addWidget(self.VAL, 4, 3, 1, 1)
        self.TYR = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TYR.sizePolicy().hasHeightForWidth())
        self.TYR.setSizePolicy(sizePolicy)
        self.TYR.setObjectName("TYR")
        self.gridLayout.addWidget(self.TYR, 4, 2, 1, 1)
        self.PRO = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PRO.sizePolicy().hasHeightForWidth())
        self.PRO.setSizePolicy(sizePolicy)
        self.PRO.setObjectName("PRO")
        self.gridLayout.addWidget(self.PRO, 3, 2, 1, 1)
        self.GLY = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GLY.sizePolicy().hasHeightForWidth())
        self.GLY.setSizePolicy(sizePolicy)
        self.GLY.setObjectName("GLY")
        self.gridLayout.addWidget(self.GLY, 1, 3, 1, 1)
        self.CYS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CYS.sizePolicy().hasHeightForWidth())
        self.CYS.setSizePolicy(sizePolicy)
        self.CYS.setObjectName("CYS")
        self.gridLayout.addWidget(self.CYS, 1, 0, 1, 1)
        self.ARG = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ARG.sizePolicy().hasHeightForWidth())
        self.ARG.setSizePolicy(sizePolicy)
        self.ARG.setObjectName("ARG")
        self.gridLayout.addWidget(self.ARG, 0, 1, 1, 1)
        self.PHE = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PHE.sizePolicy().hasHeightForWidth())
        self.PHE.setSizePolicy(sizePolicy)
        self.PHE.setObjectName("PHE")
        self.gridLayout.addWidget(self.PHE, 3, 1, 1, 1)
        self.ASN = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ASN.sizePolicy().hasHeightForWidth())
        self.ASN.setSizePolicy(sizePolicy)
        self.ASN.setObjectName("ASN")
        self.gridLayout.addWidget(self.ASN, 0, 2, 1, 1)
        self.THR = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.THR.sizePolicy().hasHeightForWidth())
        self.THR.setSizePolicy(sizePolicy)
        self.THR.setObjectName("THR")
        self.gridLayout.addWidget(self.THR, 4, 0, 1, 1)
        self.ACE = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ACE.setObjectName("ACE")
        self.gridLayout.addWidget(self.ACE, 5, 0, 1, 2)
        self.NME = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.NME.setObjectName("NME")
        self.gridLayout.addWidget(self.NME, 5, 2, 1, 2)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 420, 771, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.listWidget_ff = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_ff.setObjectName("listWidget_ff")
        QtWidgets.QListWidgetItem(self.listWidget_ff)
        QtWidgets.QListWidgetItem(self.listWidget_ff)
        QtWidgets.QListWidgetItem(self.listWidget_ff)
        self.horizontalLayout.addWidget(self.listWidget_ff)
        self.label_solv = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_solv.setFont(font)
        self.label_solv.setTextFormat(QtCore.Qt.RichText)
        self.label_solv.setObjectName("label_solv")
        self.horizontalLayout.addWidget(self.label_solv)
        self.listWidget = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget.setObjectName("listWidget")
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        QtWidgets.QListWidgetItem(self.listWidget)
        self.horizontalLayout.addWidget(self.listWidget)
        self.label_solv_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_solv_2.setFont(font)
        self.label_solv_2.setTextFormat(QtCore.Qt.RichText)
        self.label_solv_2.setObjectName("label_solv_2")
        self.horizontalLayout.addWidget(self.label_solv_2)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.push_done = QtWidgets.QPushButton(self.centralwidget)
        self.push_done.setGeometry(QtCore.QRect(610, 520, 114, 32))
        self.push_done.setObjectName("push_done")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 340, 771, 73))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sequence_text = QtWidgets.QTextBrowser(self.layoutWidget1)
        self.sequence_text.setAcceptRichText(False)
        self.sequence_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.sequence_text.setObjectName("sequence_text")
        self.horizontalLayout_2.addWidget(self.sequence_text)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 363, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.textEdit_name = QtWidgets.QTextEdit(self.widget)
        self.textEdit_name.setObjectName("textEdit_name")
        self.horizontalLayout_3.addWidget(self.textEdit_name)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(440, 20, 184, 41))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_params = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_params.setObjectName("checkBox_params")
        self.verticalLayout.addWidget(self.checkBox_params)
        self.checkBox_charge = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_charge.setObjectName("checkBox_charge")
        self.verticalLayout.addWidget(self.checkBox_charge)
        aaWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(aaWindow)
        self.statusbar.setObjectName("statusbar")
        aaWindow.setStatusBar(self.statusbar)
        self.actionNew_Structure = QtWidgets.QAction(aaWindow)
        self.actionNew_Structure.setObjectName("actionNew_Structure")

        self.retranslateUi(aaWindow)
        QtCore.QMetaObject.connectSlotsByName(aaWindow)

    def retranslateUi(self, aaWindow):
        aaWindow.setWindowTitle(QtWidgets.QApplication.translate("aaWindow", "MainWindow", None, -1))
        self.GLU.setText(QtWidgets.QApplication.translate("aaWindow", "GLU", None, -1))
        self.GLN.setText(QtWidgets.QApplication.translate("aaWindow", "GLN", None, -1))
        self.ALA.setText(QtWidgets.QApplication.translate("aaWindow", "ALA", None, -1))
        self.ASP.setText(QtWidgets.QApplication.translate("aaWindow", "ASP", None, -1))
        self.HIS.setText(QtWidgets.QApplication.translate("aaWindow", "HIS", None, -1))
        self.pushButton_17SER.setText(QtWidgets.QApplication.translate("aaWindow", "SER", None, -1))
        self.MET.setText(QtWidgets.QApplication.translate("aaWindow", "MET", None, -1))
        self.LYS.setText(QtWidgets.QApplication.translate("aaWindow", "LYS", None, -1))
        self.TRP.setText(QtWidgets.QApplication.translate("aaWindow", "TRP", None, -1))
        self.ILE.setText(QtWidgets.QApplication.translate("aaWindow", "ILE", None, -1))
        self.LEU.setText(QtWidgets.QApplication.translate("aaWindow", "LEU", None, -1))
        self.VAL.setText(QtWidgets.QApplication.translate("aaWindow", "VAL", None, -1))
        self.TYR.setText(QtWidgets.QApplication.translate("aaWindow", "TYR", None, -1))
        self.PRO.setText(QtWidgets.QApplication.translate("aaWindow", "PRO", None, -1))
        self.GLY.setText(QtWidgets.QApplication.translate("aaWindow", "GLY", None, -1))
        self.CYS.setText(QtWidgets.QApplication.translate("aaWindow", "CYS", None, -1))
        self.ARG.setText(QtWidgets.QApplication.translate("aaWindow", "ARG", None, -1))
        self.PHE.setText(QtWidgets.QApplication.translate("aaWindow", "PHE", None, -1))
        self.ASN.setText(QtWidgets.QApplication.translate("aaWindow", "ASN", None, -1))
        self.THR.setText(QtWidgets.QApplication.translate("aaWindow", "THR", None, -1))
        self.ACE.setText(QtWidgets.QApplication.translate("aaWindow", "ACE", None, -1))
        self.NME.setText(QtWidgets.QApplication.translate("aaWindow", "NME", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("aaWindow", "Force Field", None, -1))
        __sortingEnabled = self.listWidget_ff.isSortingEnabled()
        self.listWidget_ff.setSortingEnabled(False)
        self.listWidget_ff.item(0).setText(QtWidgets.QApplication.translate("aaWindow", "ff14SB", None, -1))
        self.listWidget_ff.item(1).setText(QtWidgets.QApplication.translate("aaWindow", "gaff", None, -1))
        self.listWidget_ff.item(2).setText(QtWidgets.QApplication.translate("aaWindow", "gaff2", None, -1))
        self.listWidget_ff.setSortingEnabled(__sortingEnabled)
        self.label_solv.setText(QtWidgets.QApplication.translate("aaWindow", "Solvent", None, -1))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.item(0).setText(QtWidgets.QApplication.translate("aaWindow", "Vacuum", None, -1))
        self.listWidget.item(1).setText(QtWidgets.QApplication.translate("aaWindow", "TIP3P Water", None, -1))
        self.listWidget.item(2).setText(QtWidgets.QApplication.translate("aaWindow", "TIP4P Water", None, -1))
        self.listWidget.item(3).setText(QtWidgets.QApplication.translate("aaWindow", "OPLS  Water", None, -1))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_solv_2.setText(QtWidgets.QApplication.translate("aaWindow", "Buffer", None, -1))
        self.push_done.setText(QtWidgets.QApplication.translate("aaWindow", "Done", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("aaWindow", "Sequence", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("aaWindow", "Structure Name", None, -1))
        self.checkBox_params.setText(QtWidgets.QApplication.translate("aaWindow", "Check for missing params", None, -1))
        self.checkBox_charge.setText(QtWidgets.QApplication.translate("aaWindow", "Print total charge", None, -1))
        self.actionNew_Structure.setText(QtWidgets.QApplication.translate("aaWindow", "New Structure", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aaWindow = QtWidgets.QMainWindow()
    ui = Ui_aaWindow()
    ui.setupUi(aaWindow)
    aaWindow.show()
    sys.exit(app.exec_())

