# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MD_param.ui',
# licensing of 'MD_param.ui' applies.
#
# Created: Sat Oct  6 19:30:56 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
#from write_param import parametri

class Ui_MD_param(object):
    def setupUi(self, MD_param):
        MD_param.setObjectName("MD_param")
        MD_param.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MD_param)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 500, 114, 32))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(190, 60, 362, 220))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_tstep = QtWidgets.QLabel(self.widget)
        self.label_tstep.setObjectName("label_tstep")
        self.horizontalLayout_2.addWidget(self.label_tstep)
        self.lineEdit_tstep = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_tstep.sizePolicy().hasHeightForWidth())
        self.lineEdit_tstep.setSizePolicy(sizePolicy)
        self.lineEdit_tstep.setObjectName("lineEdit_tstep")
        self.horizontalLayout_2.addWidget(self.lineEdit_tstep)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_dstlim = QtWidgets.QLabel(self.widget)
        self.label_dstlim.setObjectName("label_dstlim")
        self.horizontalLayout_3.addWidget(self.label_dstlim)
        self.lineEdit_dstlim = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_dstlim.sizePolicy().hasHeightForWidth())
        self.lineEdit_dstlim.setSizePolicy(sizePolicy)
        self.lineEdit_dstlim.setObjectName("lineEdit_dstlim")
        self.horizontalLayout_3.addWidget(self.lineEdit_dstlim)
        self.label_5 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_ntpr = QtWidgets.QLabel(self.widget)
        self.label_ntpr.setObjectName("label_ntpr")
        self.horizontalLayout_4.addWidget(self.label_ntpr)
        self.lineEdit_ntpr = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ntpr.sizePolicy().hasHeightForWidth())
        self.lineEdit_ntpr.setSizePolicy(sizePolicy)
        self.lineEdit_ntpr.setObjectName("lineEdit_ntpr")
        self.horizontalLayout_4.addWidget(self.lineEdit_ntpr)
        self.label_4 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_ntwr = QtWidgets.QLabel(self.widget)
        self.label_ntwr.setObjectName("label_ntwr")
        self.horizontalLayout_5.addWidget(self.label_ntwr)
        self.lineEdit_ntwr = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ntwr.sizePolicy().hasHeightForWidth())
        self.lineEdit_ntwr.setSizePolicy(sizePolicy)
        self.lineEdit_ntwr.setObjectName("lineEdit_ntwr")
        self.horizontalLayout_5.addWidget(self.lineEdit_ntwr)
        self.label_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ntwx = QtWidgets.QLabel(self.widget)
        self.label_ntwx.setObjectName("label_ntwx")
        self.horizontalLayout_6.addWidget(self.label_ntwx)
        self.lineEdit_ntwx = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ntwx.sizePolicy().hasHeightForWidth())
        self.lineEdit_ntwx.setSizePolicy(sizePolicy)
        self.lineEdit_ntwx.setObjectName("lineEdit_ntwx")
        self.horizontalLayout_6.addWidget(self.lineEdit_ntwx)
        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.checkBox_SHAKE = QtWidgets.QCheckBox(self.widget)
        self.checkBox_SHAKE.setObjectName("checkBox_SHAKE")
        self.verticalLayout_2.addWidget(self.checkBox_SHAKE)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_cut = QtWidgets.QLabel(self.widget)
        self.label_cut.setObjectName("label_cut")
        self.horizontalLayout.addWidget(self.label_cut)
        self.lineEdit_cut = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_cut.setObjectName("lineEdit_cut")
        self.horizontalLayout.addWidget(self.lineEdit_cut)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(330, 350, 92, 62))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_4.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_4.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget1)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_4.addWidget(self.checkBox_3)
        MD_param.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MD_param)
        self.statusbar.setObjectName("statusbar")
        MD_param.setStatusBar(self.statusbar)

        self.retranslateUi(MD_param)
        QtCore.QMetaObject.connectSlotsByName(MD_param)

        self.pushButton.clicked.connect(self.parametri)

    def retranslateUi(self, MD_param):
        MD_param.setWindowTitle(QtWidgets.QApplication.translate("MD_param", "MainWindow", None, -1))
        self.pushButton.setText(QtWidgets.QApplication.translate("MD_param", "Done", None, -1))
        self.label_tstep.setText(QtWidgets.QApplication.translate("MD_param", "Time step (ps)", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MD_param", "steps", None, -1))
        self.label_dstlim.setText(QtWidgets.QApplication.translate("MD_param", "Step Number", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MD_param", "steps", None, -1))
        self.label_ntpr.setText(QtWidgets.QApplication.translate("MD_param", "Print MD info every ", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MD_param", "steps", None, -1))
        self.label_ntwr.setText(QtWidgets.QApplication.translate("MD_param", "Print restart file every ", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MD_param", "steps", None, -1))
        self.label_ntwx.setText(QtWidgets.QApplication.translate("MD_param", "Print coordinates file every ", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MD_param", "steps", None, -1))
        self.checkBox_SHAKE.setText(QtWidgets.QApplication.translate("MD_param", "SHAKE algorithm", None, -1))
        self.label_cut.setText(QtWidgets.QApplication.translate("MD_param", "Nonbonded cutoff (A)", None, -1))
        self.checkBox.setText(QtWidgets.QApplication.translate("MD_param", "Heating", None, -1))
        self.checkBox_2.setText(QtWidgets.QApplication.translate("MD_param", "Production", None, -1))
        self.checkBox_3.setText(QtWidgets.QApplication.translate("MD_param", "Restart", None, -1))

    def parametri(self):
        mdinput = open("md.in" , "a")
        mdinput.write("dt = " + self.lineEdit_tstep.text() + "\n")
        mdinput.write("nstlim = " + self.lineEdit_dstlim.text() + "\n")
        mdinput.write("ntpr = " + self.lineEdit_ntpr.text() + "\n")
        mdinput.write("ntwr = " + self.lineEdit_ntwr.text() + "\n")
        mdinput.write("ntwx = " + self.lineEdit_ntwx.text() + "\n")
        mdinput.write("cut = " + self.lineEdit_cut.text() + "\n")

        if self.checkBox_SHAKE.isChecked():
            mdinput.write("ntc = 2\nntf=2\n")
        else:
            mdinput.write("ntc = 1\n")

        if self.checkBox.isChecked():
            mdinput.write("ntx = 1")
                

        if self.checkBox_2.isChecked():
            mdinput.write("imin = 0\nntx=5\n")

        if self.checkBox_3.isChecked():
            mdinput.write("irest = 1\n")
    
    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MD_param = QtWidgets.QMainWindow()
    ui = Ui_MD_param()
    ui.setupUi(MD_param)
    MD_param.show()
    sys.exit(app.exec_())

